//
//  DataSource.swift
//  QuoteCraft
//
//  Created by Maisam Ahmadi on 08.08.24.
//

import Foundation

class DataSource{
    let allQuotes: [Quote] = [
        
        Quote(text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh", category: "Motivational"),
        Quote(text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", category: "Motivational"),
        Quote(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", category: "Motivational"),
        Quote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Motivational"),
        Quote(text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "Motivational"),
        Quote(text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Motivational"),
        Quote(text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Motivational"),
        Quote(text: "The harder the battle, the sweeter the victory.", author: "Les Brown", category: "Motivational"),
        Quote(text: "Dream big and dare to fail.", author: "Norman Vaughan", category: "Motivational"),
        Quote(text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Motivational"),
        Quote(text: "Don't limit your challenges. Challenge your limits.", author: "Unknown", category: "Motivational"),
        Quote(text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill", category: "Motivational"),
        Quote(text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe", category: "Motivational"),
        Quote(text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Motivational"),
        Quote(text: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", author: "Christian D. Larson", category: "Motivational"),
        Quote(text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett", category: "Motivational"),
        Quote(text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn", category: "Motivational"),
        Quote(text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis", category: "Motivational"),
        Quote(text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt", category: "Motivational"),
        Quote(text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Motivational"),
        Quote(text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau", category: "Motivational"),
        Quote(text: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "Motivational"),
        Quote(text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson", category: "Motivational"),
        Quote(text: "Success is not in what you have, but who you are.", author: "Bo Bennett", category: "Motivational"),
        Quote(text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Motivational"),
        Quote(text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill", category: "Motivational"),
        Quote(text: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis", category: "Motivational"),
        Quote(text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "Motivational"),
        Quote(text: "Success is not just what you accomplish in your life; it is about what you inspire others to do.", author: "Unknown", category: "Motivational"),
        Quote(text: "Fall seven times and stand up eight.", author: "Japanese Proverb", category: "Motivational"),
        Quote(text: "Some people dream of success while others wake up and work.", author: "Unknown", category: "Motivational"),
        Quote(text: "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.", author: "Jim Rohn", category: "Motivational"),
        Quote(text: "I failed my way to success.", author: "Thomas Edison", category: "Motivational"),
        Quote(text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi", category: "Motivational"),
        Quote(text: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg", category: "Motivational"),
        Quote(text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "Motivational"),
        Quote(text: "You only live once, but if you do it right, once is enough.", author: "Mae West", category: "Motivational"),
        Quote(text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson", category: "Motivational"),
        Quote(text: "To accomplish great things, we must not only act, but also dream, not only plan, but also believe.", author: "Anatole France", category: "Motivational"),
        Quote(text: "Don't be discouraged. It's often the last key in the bunch that opens the lock.", author: "Unknown", category: "Motivational"),
        Quote(text: "The secret to getting ahead is getting started.", author: "Mark Twain", category: "Motivational"),
        Quote(text: "I never dreamed about success. I worked for it.", author: "Estee Lauder", category: "Motivational"),
        Quote(text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett", category: "Motivational"),
        Quote(text: "Success is not in what you have, but who you are.", author: "Bo Bennett", category: "Motivational"),
        Quote(text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "Motivational"),
        Quote(text: "Your limitation—it's only your imagination.", author: "Unknown", category: "Motivational"),
        Quote(text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Motivational"),
        
        
        
        
        
        
        Quote(text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown, Jr.", category: "Inspirational"),
        Quote(text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", category: "Inspirational"),
        Quote(text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky", category: "Inspirational"),
        Quote(text: "Act as if what you do makes a difference. It does.", author: "William James", category: "Inspirational"),
        Quote(text: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman", category: "Inspirational"),
        Quote(text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson", category: "Inspirational"),
        Quote(text: "No matter what people tell you, words and ideas can change the world.", author: "Robin Williams", category: "Inspirational"),
        Quote(text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Inspirational"),
        Quote(text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair", category: "Inspirational"),
        Quote(text: "You are enough just as you are.", author: "Meghan Markle", category: "Inspirational"),
        Quote(text: "The only impossible journey is the one you never begin.", author: "Tony Robbins", category: "Inspirational"),
        Quote(text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll", category: "Inspirational"),
        Quote(text: "Your life is your story, and the adventure ahead of you is the journey to fulfill your own purpose and potential.", author: "Kerry Washington", category: "Inspirational"),
        Quote(text: "You get in life what you have the courage to ask for.", author: "Oprah Winfrey", category: "Inspirational"),
        Quote(text: "Don't wait for the perfect moment, take the moment and make it perfect.", author: "Zoey Sayward", category: "Inspirational"),
        Quote(text: "Happiness is not by chance, but by choice.", author: "Jim Rohn", category: "Inspirational"),
        Quote(text: "The best way to predict the future is to create it.", author: "Peter Drucker", category: "Inspirational"),
        Quote(text: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain", category: "Inspirational"),
        Quote(text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller", category: "Inspirational"),
        Quote(text: "To be the best, you must be able to handle the worst.", author: "Wilson Kanadi", category: "Inspirational"),
        Quote(text: "The only way to do great work is to love what you do.", author: "Steve Jobs", category: "Inspirational"),
        Quote(text: "The power of imagination makes us infinite.", author: "John Muir", category: "Inspirational"),
        Quote(text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt", category: "Inspirational"),
        Quote(text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar", category: "Inspirational"),
        Quote(text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill", category: "Inspirational"),
        Quote(text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen R. Covey", category: "Inspirational"),
        Quote(text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius", category: "Inspirational"),
        Quote(text: "The secret of getting ahead is getting started.", author: "Mark Twain", category: "Inspirational"),
        Quote(text: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn", category: "Inspirational"),
        Quote(text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Inspirational"),
        Quote(text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", category: "Inspirational"),
        Quote(text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon", category: "Inspirational"),
        Quote(text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis", category: "Inspirational"),
        Quote(text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs", category: "Inspirational"),
        Quote(text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson", category: "Inspirational"),
        Quote(text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt", category: "Inspirational"),
        Quote(text: "Opportunities don't happen. You create them.", author: "Chris Grosser", category: "Inspirational"),
        Quote(text: "Success is not in what you have, but who you are.", author: "Bo Bennett", category: "Inspirational"),
        Quote(text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney", category: "Inspirational"),
        Quote(text: "Your limitation—it's only your imagination.", author: "Unknown", category: "Inspirational"),
        Quote(text: "Great things never come from comfort zones.", author: "Unknown", category: "Inspirational"),
        Quote(text: "Dream it. Wish it. Do it.", author: "Unknown", category: "Inspirational"),
        Quote(text: "Success doesn’t just find you. You have to go out and get it.", author: "Unknown", category: "Inspirational"),
        Quote(text: "Dream bigger. Do bigger.", author: "Unknown", category: "Inspirational"),
        Quote(text: "Little things make big days.", author: "Unknown", category: "Inspirational"),
        Quote(text: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown", category: "Inspirational"),
        
        
        
        
        
        
        Quote(text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom"),
        Quote(text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu", category: "Wisdom"),
        Quote(text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein", category: "Wisdom"),
        Quote(text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Wisdom"),
        Quote(text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom"),
        Quote(text: "Patience is the companion of wisdom.", author: "Saint Augustine", category: "Wisdom"),
        Quote(text: "The invariable mark of wisdom is to see the miraculous in the common.", author: "Ralph Waldo Emerson", category: "Wisdom"),
        Quote(text: "Wisdom is the reward you get for a lifetime of listening when you would rather have talked.", author: "Mark Twain", category: "Wisdom"),
        Quote(text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Wisdom"),
        Quote(text: "Wisdom is knowing what to do next; virtue is doing it.", author: "David Starr Jordan", category: "Wisdom"),
        Quote(text: "The wise man does at once what the fool does finally.", author: "Baltasar Gracian", category: "Wisdom"),
        Quote(text: "The greatest wisdom is seeing through appearances.", author: "Atisa", category: "Wisdom"),
        Quote(text: "Wisdom outweighs any wealth.", author: "Sophocles", category: "Wisdom"),
        Quote(text: "Silence is the sleep that nourishes wisdom.", author: "Francis Bacon", category: "Wisdom"),
        Quote(text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix", category: "Wisdom"),
        Quote(text: "Wisdom is the daughter of experience.", author: "Leonardo da Vinci", category: "Wisdom"),
        Quote(text: "Wisdom begins in wonder.", author: "Socrates", category: "Wisdom"),
        Quote(text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom"),
        Quote(text: "He who learns must suffer. And even in our sleep pain that cannot forget falls drop by drop upon the heart, and in our own despair, against our will, comes wisdom to us by the awful grace of God.", author: "Aeschylus", category: "Wisdom"),
        Quote(text: "A loving heart is the truest wisdom.", author: "Charles Dickens", category: "Wisdom"),
        Quote(text: "To conquer fear is the beginning of wisdom.", author: "Bertrand Russell", category: "Wisdom"),
        Quote(text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein", category: "Wisdom"),
        Quote(text: "The simple things are also the most extraordinary things, and only the wise can see them.", author: "Paulo Coelho", category: "Wisdom"),
        Quote(text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom"),
        Quote(text: "Patience is the companion of wisdom.", author: "Saint Augustine", category: "Wisdom"),
        Quote(text: "Turn your wounds into wisdom.", author: "Oprah Winfrey", category: "Wisdom"),
        Quote(text: "The wise man does at once what the fool does finally.", author: "Baltasar Gracian", category: "Wisdom"),
        Quote(text: "Wisdom is the reward you get for a lifetime of listening when you would rather have talked.", author: "Mark Twain", category: "Wisdom"),
        Quote(text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein", category: "Wisdom"),
        Quote(text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom"),
        Quote(text: "Silence is the sleep that nourishes wisdom.", author: "Francis Bacon", category: "Wisdom"),
        Quote(text: "Patience is the companion of wisdom.", author: "Saint Augustine", category: "Wisdom"),
        Quote(text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom"),
        Quote(text: "Wisdom is the daughter of experience.", author: "Leonardo da Vinci", category: "Wisdom"),
        Quote(text: "Wisdom begins in wonder.", author: "Socrates", category: "Wisdom"),
        Quote(text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix", category: "Wisdom"),
        Quote(text: "The greatest wisdom is seeing through appearances.", author: "Atisa", category: "Wisdom"),
        Quote(text: "Silence is the sleep that nourishes wisdom.", author: "Francis Bacon", category: "Wisdom"),
        Quote(text: "The simple things are also the most extraordinary things, and only the wise can see them.", author: "Paulo Coelho", category: "Wisdom"),
        Quote(text: "Wisdom outweighs any wealth.", author: "Sophocles", category: "Wisdom"),
        Quote(text: "Wisdom is knowing what to do next; virtue is doing it.", author: "David Starr Jordan", category: "Wisdom"),
        Quote(text: "He who learns must suffer. And even in our sleep pain that cannot forget falls drop by drop upon the heart, and in our own despair, against our will, comes wisdom to us by the awful grace of God.", author: "Aeschylus", category: "Wisdom"),
        Quote(text: "A loving heart is the truest wisdom.", author: "Charles Dickens", category: "Wisdom"),
        Quote(text: "The wise man does at once what the fool does finally.", author: "Baltasar Gracian", category: "Wisdom"),
        Quote(text: "To conquer fear is the beginning of wisdom.", author: "Bertrand Russell", category: "Wisdom"),
        Quote(text: "The only true wisdom is in knowing you know nothing.", author: "Socrates", category: "Wisdom"),
        Quote(text: "Patience is the companion of wisdom.", author: "Saint Augustine", category: "Wisdom"),
        Quote(text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle", category: "Wisdom"),
        Quote(text: "Wisdom is the reward you get for a lifetime of listening when you would rather have talked.", author: "Mark Twain", category: "Wisdom"),
        
        
        
        
        
        Quote(text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama", category: "Happiness"),
        Quote(text: "The purpose of our lives is to be happy.", author: "Dalai Lama", category: "Happiness"),
        Quote(text: "Happiness depends upon ourselves.", author: "Aristotle", category: "Happiness"),
        Quote(text: "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.", author: "Unknown", category: "Happiness"),
        Quote(text: "The secret of happiness is to admire without desiring.", author: "Carl Sandburg", category: "Happiness"),
        Quote(text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn", category: "Happiness"),
        Quote(text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin D. Roosevelt", category: "Happiness"),
        Quote(text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi", category: "Happiness"),
        Quote(text: "Happiness is not a goal...it's a by-product of a life well-lived.", author: "Eleanor Roosevelt", category: "Happiness"),
        Quote(text: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson", category: "Happiness"),
        Quote(text: "Happiness is not the absence of problems, it's the ability to deal with them.", author: "Steve Maraboli", category: "Happiness"),
        Quote(text: "Happiness is a warm puppy.", author: "Charles M. Schulz", category: "Happiness"),
        Quote(text: "Happiness is the secret to all beauty. There is no beauty without happiness.", author: "Christian Dior", category: "Happiness"),
        Quote(text: "Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude.", author: "Denis Waitley", category: "Happiness"),
        Quote(text: "Happiness lies in the joy of achievement and the thrill of creative effort.", author: "Franklin D. Roosevelt", category: "Happiness"),
        Quote(text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle", category: "Happiness"),
        Quote(text: "Happiness is a direction, not a place.", author: "Sydney J. Harris", category: "Happiness"),
        Quote(text: "Happiness is not the key to success. Success is the key to happiness. If you love what you are doing, you will be successful.", author: "Albert Schweitzer", category: "Happiness"),
        Quote(text: "Happiness is only real when shared.", author: "Jon Krakauer", category: "Happiness"),
        Quote(text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn", category: "Happiness"),
        Quote(text: "Happiness is not a goal; it is a by-product.", author: "Eleanor Roosevelt", category: "Happiness"),
        Quote(text: "Happiness is a choice that requires effort at times.", author: "Aeschylus", category: "Happiness"),
        Quote(text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin D. Roosevelt", category: "Happiness"),
        Quote(text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi", category: "Happiness"),
        Quote(text: "Happiness is not a station you arrive at, but a manner of traveling.", author: "Margaret Lee Runbeck", category: "Happiness"),
        Quote(text: "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.", author: "Unknown", category: "Happiness"),
        Quote(text: "The secret of happiness is to admire without desiring.", author: "Carl Sandburg", category: "Happiness"),
        Quote(text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn", category: "Happiness"),
        Quote(text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle", category: "Happiness"),
        Quote(text: "Happiness is a warm puppy.", author: "Charles M. Schulz", category: "Happiness"),
        Quote(text: "Happiness is the secret to all beauty. There is no beauty without happiness.", author: "Christian Dior", category: "Happiness"),
        Quote(text: "Happiness is not the absence of problems, it's the ability to deal with them.", author: "Steve Maraboli", category: "Happiness"),
        Quote(text: "Happiness cannot be traveled to, owned, earned, worn or consumed. Happiness is the spiritual experience of living every minute with love, grace, and gratitude.", author: "Denis Waitley", category: "Happiness"),
        Quote(text: "Happiness lies in the joy of achievement and the thrill of creative effort.", author: "Franklin D. Roosevelt", category: "Happiness"),
        Quote(text: "Happiness is the meaning and the purpose of life, the whole aim and end of human existence.", author: "Aristotle", category: "Happiness"),
        Quote(text: "Happiness is a direction, not a place.", author: "Sydney J. Harris", category: "Happiness"),
        Quote(text: "Happiness is not the key to success. Success is the key to happiness. If you love what you are doing, you will be successful.", author: "Albert Schweitzer", category: "Happiness"),
        Quote(text: "Happiness is only real when shared.", author: "Jon Krakauer", category: "Happiness"),
        Quote(text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn", category: "Happiness"),
        Quote(text: "Happiness is not a goal; it is a by-product.", author: "Eleanor Roosevelt", category: "Happiness"),
        Quote(text: "Happiness is a choice that requires effort at times.", author: "Aeschylus", category: "Happiness"),
        Quote(text: "Happiness is not in the mere possession of money; it lies in the joy of achievement, in the thrill of creative effort.", author: "Franklin D. Roosevelt", category: "Happiness"),
        Quote(text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi", category: "Happiness"),
        Quote(text: "Happiness is not a station you arrive at, but a manner of traveling.", author: "Margaret Lee Runbeck", category: "Happiness"),
        Quote(text: "Happiness is the art of never holding in your mind the memory of any unpleasant thing that has passed.", author: "Unknown", category: "Happiness"),
        Quote(text: "The secret of happiness is to admire without desiring.", author: "Carl Sandburg", category: "Happiness"),
        
        
        
        
        
        
        Quote(text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader", category: "Leadership"),
        Quote(text: "Leadership is the capacity to translate vision into reality.", author: "Warren Bennis", category: "Leadership"),
        Quote(text: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", author: "Ronald Reagan", category: "Leadership"),
        Quote(text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John C. Maxwell", category: "Leadership"),
        Quote(text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy", category: "Leadership"),
        Quote(text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader", category: "Leadership"),
        Quote(text: "Leadership is the capacity to translate vision into reality.", author: "Warren Bennis", category: "Leadership"),
        Quote(text: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", author: "Ronald Reagan", category: "Leadership"),
        Quote(text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John C. Maxwell", category: "Leadership"),
        Quote(text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy", category: "Leadership"),
        Quote(text: "The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint to keep from meddling with them while they do it.", author: "Theodore Roosevelt", category: "Leadership"),
        Quote(text: "The very essence of leadership is that you have to have a vision.", author: "Theodore M. Hesburgh", category: "Leadership"),
        Quote(text: "The art of leadership is saying no, not yes. It is very easy to say yes.", author: "Tony Blair", category: "Leadership"),
        Quote(text: "Leadership is the art of getting someone else to do something you want done because he wants to do it.", author: "Dwight D. Eisenhower", category: "Leadership"),
        Quote(text: "The quality of a leader is reflected in the standards they set for themselves.", author: "Ray Kroc", category: "Leadership"),
        Quote(text: "The key to successful leadership today is influence, not authority.", author: "Kenneth Blanchard", category: "Leadership"),
        Quote(text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader", category: "Leadership"),
        Quote(text: "Leadership is the capacity to translate vision into reality.", author: "Warren Bennis", category: "Leadership"),
        Quote(text: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", author: "Ronald Reagan", category: "Leadership"),
        Quote(text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John C. Maxwell", category: "Leadership"),
        Quote(text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy", category: "Leadership"),
        Quote(text: "The very essence of leadership is that you have to have a vision.", author: "Theodore M. Hesburgh", category: "Leadership"),
        Quote(text: "The art of leadership is saying no, not yes. It is very easy to say yes.", author: "Tony Blair", category: "Leadership"),
        Quote(text: "Leadership is the art of getting someone else to do something you want done because he wants to do it.", author: "Dwight D. Eisenhower", category: "Leadership"),
        Quote(text: "The quality of a leader is reflected in the standards they set for themselves.", author: "Ray Kroc", category: "Leadership"),
        Quote(text: "The key to successful leadership today is influence, not authority.", author: "Kenneth Blanchard", category: "Leadership"),
        Quote(text: "A good leader leads the people from above them. A great leader leads the people from within them.", author: "M. D. Arnold", category: "Leadership"),
        Quote(text: "To handle yourself, use your head; to handle others, use your heart.", author: "Eleanor Roosevelt", category: "Leadership"),
        Quote(text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader", category: "Leadership"),
        Quote(text: "Leadership is the capacity to translate vision into reality.", author: "Warren Bennis", category: "Leadership"),
        Quote(text: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", author: "Ronald Reagan", category: "Leadership"),
        Quote(text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John C. Maxwell", category: "Leadership"),
        Quote(text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy", category: "Leadership"),
        Quote(text: "The function of leadership is to produce more leaders, not more followers.", author: "Ralph Nader", category: "Leadership"),
        Quote(text: "Leadership is the capacity to translate vision into reality.", author: "Warren Bennis", category: "Leadership"),
        Quote(text: "The greatest leader is not necessarily the one who does the greatest things. He is the one that gets the people to do the greatest things.", author: "Ronald Reagan", category: "Leadership"),
        Quote(text: "A leader is one who knows the way, goes the way, and shows the way.", author: "John C. Maxwell", category: "Leadership"),
        Quote(text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy", category: "Leadership"),
        Quote(text: "The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint to keep from meddling with them while they do it.", author: "Theodore Roosevelt", category: "Leadership"),
        Quote(text: "The very essence of leadership is that you have to have a vision.", author: "Theodore M. Hesburgh", category: "Leadership"),
        Quote(text: "The art of leadership is saying no, not yes. It is very easy to say yes.", author: "Tony Blair", category: "Leadership"),
        Quote(text: "Leadership is the art of getting someone else to do something you want done because he wants to do it.", author: "Dwight D. Eisenhower", category: "Leadership"),
        Quote(text: "The quality of a leader is reflected in the standards they set for themselves.", author: "Ray Kroc", category: "Leadership"),
        Quote(text: "The key to successful leadership today is influence, not authority.", author: "Kenneth Blanchard", category: "Leadership")
        
        
        
        
        
    ]
}
